#!/usr/bin/env bash

set -e

OS="$(uname -s)"

export PYENV_ROOT="$HOME/.pyenv"

if [ -x "$PYENV_ROOT/bin/pyenv" ]; then
    echo "pyenv already installed: $("$PYENV_ROOT/bin/pyenv" --version)"
    exit 0
fi

if [ "$OS" = "Darwin" ]; then
    # macOS: Xcode CLT provides most build deps; install remaining ones via brew
    brew install openssl readline sqlite3 xz zlib tcl-tk
else
    sudo apt install -y make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
    libffi-dev liblzma-dev git
fi

curl https://pyenv.run | bash

export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

LATEST_PYTHON=$(pyenv install --list | grep -E '^\s*[0-9]+\.[0-9]+\.[0-9]+$' | tail -1 | tr -d '[:space:]')
pyenv install --skip-existing "$LATEST_PYTHON"

pyenv global "$(pyenv versions --bare | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)"

pip install --upgrade pip
