#!/usr/bin/env bash

set -e

sudo apt -y update
sudo apt -y install git ripgrep jq tldr unzip build-essential tmux tree htop xclip git-delta

if [ ! -d "$HOME/personal/fzf" ]; then
    git clone https://github.com/junegunn/fzf.git "$HOME/personal/fzf"
fi
"$HOME/personal/fzf/install" --all
