#!/usr/bin/env bash

sudo apt install -y make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
libffi-dev liblzma-dev git

export PYENV_ROOT="$HOME/.pyenv"

curl https://pyenv.run | bash > /dev/null 2>&1

export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)" > /dev/null 2>&1
eval "$(pyenv virtualenv-init -)" > /dev/null 2>&1

pyenv install --skip-existing $(pyenv install --list | grep -E '^\s*[0-9]+\.[0-9]+\.[0-9]+$' | tail -1 | tr -d '[:space:]') > /dev/null 2>&1

pyenv global $(pyenv versions --bare | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1) > /dev/null 2>&1

pip install --upgrade pip > /dev/null 2>&1
