#!/usr/bin/env bash

sudo apt install tmux

TPM_DIR="$HOME/personal/dev/env/.config/tmux/plugins/tpm"

if [ ! -d $TPM_DIR ]; then
    git clone https://github.com/tmux-plugins/tpm $TPM_DIR
fi

"$TPM_DIR/bin/install_plugins"
