#!/usr/bin/env bash

sudo apt install tmux

export TMUX_PLUGIN_MANAGER_PATH="$HOME/personal/dev/env/.config/tmux/plugins"
TPM_DIR="$TMUX_PLUGIN_MANAGER_PATH/tpm"

if [ ! -d $TPM_DIR ]; then
    git clone https://github.com/tmux-plugins/tpm $TPM_DIR
fi

"$TPM_DIR/bin/install_plugins"
